# WEB SCARPING AND DATA CLEANING

In [22]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [23]:
link='https://www.worldometers.info/coronavirus/'
r=requests.get(link)
soup=BeautifulSoup(r.text,'html.parser')

In [24]:
x=soup.find('tbody')

In [25]:
country=[]
total_cases=[]
new_cases=[]
total_deaths=[]
new_deaths=[]
total_recovered=[]
new_recovered=[]
active_cases=[]
serious=[]
TopCases_1MPop=[]
Death_1MPop=[]
total_tests=[]
Tests_1MPop=[]
population=[]
for row in x.find_all('tr'):
    col=row.find_all('td')
    country.append(col[1].text)
    total_cases.append(col[2].text)
    new_cases.append(col[3].text)
    total_deaths.append(col[4].text)
    new_deaths.append(col[5].text)
    total_recovered.append(col[6].text)
    new_recovered.append(col[7].text)
    active_cases.append(col[8].text)
    serious.append(col[9].text)
    TopCases_1MPop.append(col[10].text)
    Death_1MPop.append(col[11].text)
    total_tests.append(col[12].text)
    Tests_1MPop.append(col[13].text)
    population.append(col[14].text)

In [26]:
data=pd.DataFrame({'Country':country,'Total Cases':total_cases,'New Cases':new_cases,'Total Deaths':total_deaths,'New Deaths':new_deaths,'Total Recovered':total_recovered,'New Recovered':new_recovered,'Active Cases':active_cases,'Serious':serious,'Top Cases/1MPop':TopCases_1MPop,'Deaths/1MPop':Death_1MPop,'Total Tests':total_tests,'Tests/1MPop':Tests_1MPop,'Population':population})
data

,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases,Serious,Top Cases/1MPop,Deaths/1MPop,Total Tests,Tests/1MPop,Population
0,\nNorth America\n,"131,889,132",,"1,695,941",,"127,665,129",+350,"2,528,062","6,095",,,,,
1,\nAsia\n,"221,500,265",,"1,553,662",,"205,673,091",,"14,273,512","14,733",,,,,
2,\nEurope\n,"253,406,198",,"2,101,824",,"248,754,104",+474,"2,550,270","4,453",,,,,
3,\nSouth America\n,"70,200,879",,"1,367,332",,"66,683,585",,"2,149,962","8,953",,,,,
4,\nOceania\n,"14,895,771",,"33,015",,"14,752,388",,"110,368",31,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Tokelau,80,,,,,,80,,"58,055",,,,"1,378"
235,Vatican City,29,,,,29,,0,,"36,295",,,,799
236,Western Sahara,10,,1,,9,,0,,16,2,,,"626,161"
237,MS Zaandam,9,,2,,7,,0,,,,,,
238,China,"503,302",,"5,272",,"379,053",,"118,977",N/A,347,4,"160,000,000","110,461","1,448,471,400"

In [27]:
data['Country'] = data['Country'].str.replace('\n', '')
data['Country']=data['Country'].replace('',np.nan)
data=data.dropna(subset=['Country'])
for col in data.columns[1:]:
    data[col] = data[col].astype(str)
    data[col] = data[col].str.strip()
    data[col] = data[col].str.replace(',', '')
    data[col] = data[col].str.replace('+', '')
    data[col] = pd.to_numeric(data[col], errors='coerce')
data.head(10)

,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases,Serious,Top Cases/1MPop,Deaths/1MPop,Total Tests,Tests/1MPop,Population
0,North America,131889132,NaN,1695941.0,NaN,127665129.0,350.0,2528062.0,6095.0,NaN,NaN,NaN,NaN,NaN
1,Asia,221500265,NaN,1553662.0,NaN,205673091.0,NaN,14273512.0,14733.0,NaN,NaN,NaN,NaN,NaN
2,Europe,253406198,NaN,2101824.0,NaN,248754104.0,474.0,2550270.0,4453.0,NaN,NaN,NaN,NaN,NaN
3,South America,70200879,NaN,1367332.0,NaN,66683585.0,NaN,2149962.0,8953.0,NaN,NaN,NaN,NaN,NaN
4,Oceania,14895771,NaN,33015.0,NaN,14752388.0,NaN,110368.0,31.0,NaN,NaN,NaN,NaN,NaN
5,Africa,12860924,NaN,258892.0,NaN,12090808.0,NaN,511224.0,529.0,NaN,NaN,NaN,NaN,NaN
7,World,704753890,0.0,7010681.0,0.0,675619811.0,790.0,22123398.0,34794.0,90413.0,899.4,NaN,NaN,NaN
8,USA,111820082,NaN,1219487.0,NaN,109814428.0,NaN,786167.0,940.0,333985.0,3642.0,1.186852e+09,3544901.0,3.348053e+08
9,India,45035393,NaN,533570.0,NaN,NaN,NaN,NaN,NaN,32016.0,379.0,9.358795e+08,665334.0,1.406632e+09
10,France,40138560,NaN,167642.0,NaN,39970918.0,NaN,0.0,NaN,612013.0,2556.0,2.714902e+08,4139547.0,6.558452e+07

In [28]:
data.isna().sum()

Country              0
Total Cases          0
New Cases          237
Total Deaths         5
New Deaths         237
Total Recovered     48
New Recovered      230
Active Cases        47
Serious            179
Top Cases/1MPop      8
Deaths/1MPop        13
Total Tests         25
Tests/1MPop         25
Population           9
dtype: int64

In [29]:
data['New Cases'].fillna(0, inplace=True)
data['Total Deaths'].fillna(data['Total Deaths'].median(), inplace=True)
data['New Deaths'].fillna(0, inplace=True)
data['Total Recovered'].fillna(data['Total Recovered'].mean(), inplace=True)
data['New Recovered'].fillna(0, inplace=True)
data['Active Cases'].fillna(data['Active Cases'].mean(), inplace=True)
data['Serious'].fillna(0, inplace=True)
data['Top Cases/1MPop'].fillna(data['Top Cases/1MPop'].mean(), inplace=True)
data['Deaths/1MPop'].fillna(data['Deaths/1MPop'].mean(), inplace=True)
data['Total Tests'].fillna(data['Total Tests'].mean(), inplace=True)
data['Tests/1MPop'].fillna(data['Tests/1MPop'].mean(), inplace=True)
data['Population'].fillna(data['Population'].mean(), inplace=True)

In [30]:
data.describe()

,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases,Serious,Top Cases/1MPop,Deaths/1MPop,Total Tests,Tests/1MPop,Population
count,2.380000e+02,238.0,2.380000e+02,238.0,2.380000e+02,238.000000,2.380000e+02,238.000000,238.000000,238.000000,2.380000e+02,2.380000e+02,2.380000e+02
mean,8.883449e+06,0.0,8.842386e+04,0.0,1.006214e+07,10.243697,2.636781e+05,304.474790,202460.960870,1275.668444,3.298829e+07,2.155978e+06,3.469404e+07
std,5.193031e+07,0.0,5.110231e+05,0.0,4.961139e+07,71.864789,1.722159e+06,2552.599489,202334.192704,1271.373988,1.133791e+08,3.450208e+06,1.359796e+08
min,9.000000e+00,0.0,1.000000e+00,0.0,2.000000e+00,0.000000,0.000000e+00,0.000000,16.000000,2.000000,7.850000e+03,5.093000e+03,7.990000e+02
25%,2.741875e+04,0.0,2.282500e+02,0.0,4.156800e+04,0.000000,7.325000e+01,0.000000,23722.750000,184.500000,4.475890e+05,2.305802e+05,5.749662e+05
50%,2.320425e+05,0.0,2.570000e+03,0.0,7.760020e+05,0.000000,1.558500e+03,0.000000,137260.500000,990.000000,3.086912e+06,1.189580e+06,6.706560e+06
75%,1.565481e+06,0.0,1.707325e+04,0.0,1.006214e+07,0.000000,1.604828e+05,0.000000,320003.750000,1983.250000,3.213843e+07,2.155978e+06,2.886144e+07
max,7.047539e+08,0.0,7.010681e+06,0.0,6.756198e+08,790.000000,2.212340e+07,34794.000000,771655.000000,6595.000000,1.186852e+09,2.330212e+07,1.448471e+09

In [31]:
data.to_csv("Covid-19.csv")